apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: clusters.clusterregistry.k8s.io
spec:
  group: clusterregistry.k8s.io
  version: v1alpha1
  scope: Cluster
  names:
    plural: clusters
    singular: cluster
    kind: Cluster
  validation:
    openAPIV3Schema:
      properties:
        spec:
          type: object
          kubernetesAPIEndpoints:
            type: object
            properties:
            serverEndpoints:
              type: array
              items:
                type: object
                properties:
                  clientCIDR:
                    type: string
                  serverAddress:
                    type: string
            caBundle:
              type: byte
          authInfo:
            type: object
            properties:
            providers:
              type: array
              items:
                type: object
                properties:
                  name:
                    type: string
                  type:
                    type: object
                    properties:
                      name:
                        type: string
                  config:
                    type: array
                    items:
                      type: object
                      properties:
                        key:
                          type: string
                        value:
                          type: string
